[tool.poetry]
name = "kuhn-poker-cfr"
version = "0.1.0"
description = ""
authors = ["Max Breslin <maxbreslin@u.northwestern.edu>", "Harry Guan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ruff = "^0.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
